-- Tabla de canciones
CREATE TABLE tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number VARCHAR(10) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL,
  soundcloud_url TEXT,
  duration VARCHAR(10),
  edition VARCHAR(100),
  notes TEXT,
  accent VARCHAR(7) DEFAULT '#a855f7',
  bg TEXT DEFAULT 'linear-gradient(135deg, #0d0d1a 0%, #1a0533 45%, #2d1b69 100%)',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de artículos
CREATE TABLE articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  track_id BIGINT REFERENCES tracks(id) ON DELETE SET NULL,
  author VARCHAR(255),
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para mejor rendimiento
CREATE INDEX idx_tracks_number ON tracks(number);
CREATE INDEX idx_tracks_created_at ON tracks(created_at);
CREATE INDEX idx_articles_track_id ON articles(track_id);
CREATE INDEX idx_articles_published ON articles(published);
CREATE INDEX idx_articles_created_at ON articles(created_at);

-- Políticas de seguridad (Row Level Security)
ALTER TABLE tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Política para tracks (acceso completo para desarrollo)
CREATE POLICY "Enable all operations for all users on tracks" ON tracks
  FOR ALL USING (true) WITH CHECK (true);

-- Política para articles (acceso completo para desarrollo)
CREATE POLICY "Enable all operations for all users on articles" ON articles
  FOR ALL USING (true) WITH CHECK (true);

-- NOTA: Para producción, considera restringir el acceso solo a usuarios autenticados:
-- CREATE POLICY "Enable insert for authenticated users" ON tracks
--   FOR INSERT WITH CHECK (auth.role() = 'authenticated');
-- CREATE POLICY "Enable update for authenticated users" ON tracks
--   FOR UPDATE USING (auth.role() = 'authenticated');
-- CREATE POLICY "Enable delete for authenticated users" ON tracks
--   FOR DELETE USING (auth.role() = 'authenticated');

-- Función para actualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para actualizar updated_at
CREATE TRIGGER update_tracks_updated_at 
  BEFORE UPDATE ON tracks 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_articles_updated_at 
  BEFORE UPDATE ON articles 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
